#############################################################################
# Makefile for building: build/debug/DNDHLPR
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  Messages.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt5/bin/qmake -spec linux-g++-64 -o Makefile Messages.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/debug/.moc -Ibuild/debug/.ui -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64
QMAKE         = /usr/lib/x86_64-linux-gnu/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = DNDHLPR1.0.0
DISTDIR = /home/colt/Desktop/Not\ CPSC/DNDHelper/build/debug/.obj/DNDHLPR1.0.0
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/X11R6/lib64 -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/debug/.obj/

####### Files

SOURCES       = main.cpp \
		menu_window/mainwindow.cpp \
		menu_window/mapwindow.cpp \
		menu_window/districtmap.cpp \
		district/baxter_theatre_district.cpp \
		district/bernard_district.cpp \
		district/blue_district.cpp \
		district/border_district.cpp \
		district/capital_district.cpp \
		district/capital_mausoleum_district.cpp \
		district/central_market_district.cpp \
		district/church_of_anne_district.cpp \
		district/damen_district.cpp \
		district/east_a_district.cpp \
		district/east_b_district.cpp \
		district/east_fishery_district.cpp \
		district/fishery_district.cpp \
		district/flower_square_district.cpp \
		district/hotel_district.cpp \
		district/lower_west_district.cpp \
		district/north_district.cpp \
		district/north_fishery_district.cpp \
		district/north_market_district.cpp \
		district/sea_district.cpp \
		district/south_fishery_district.cpp \
		district/south_market_district.cpp \
		district/st_abraham_district.cpp \
		district/steam_mines_district.cpp \
		district/stone_district.cpp build/debug/.moc/moc_mainwindow.cpp \
		build/debug/.moc/moc_mapwindow.cpp \
		build/debug/.moc/moc_districtmap.cpp
OBJECTS       = build/debug/.obj/main.o \
		build/debug/.obj/mainwindow.o \
		build/debug/.obj/mapwindow.o \
		build/debug/.obj/districtmap.o \
		build/debug/.obj/baxter_theatre_district.o \
		build/debug/.obj/bernard_district.o \
		build/debug/.obj/blue_district.o \
		build/debug/.obj/border_district.o \
		build/debug/.obj/capital_district.o \
		build/debug/.obj/capital_mausoleum_district.o \
		build/debug/.obj/central_market_district.o \
		build/debug/.obj/church_of_anne_district.o \
		build/debug/.obj/damen_district.o \
		build/debug/.obj/east_a_district.o \
		build/debug/.obj/east_b_district.o \
		build/debug/.obj/east_fishery_district.o \
		build/debug/.obj/fishery_district.o \
		build/debug/.obj/flower_square_district.o \
		build/debug/.obj/hotel_district.o \
		build/debug/.obj/lower_west_district.o \
		build/debug/.obj/north_district.o \
		build/debug/.obj/north_fishery_district.o \
		build/debug/.obj/north_market_district.o \
		build/debug/.obj/sea_district.o \
		build/debug/.obj/south_fishery_district.o \
		build/debug/.obj/south_market_district.o \
		build/debug/.obj/st_abraham_district.o \
		build/debug/.obj/steam_mines_district.o \
		build/debug/.obj/stone_district.o \
		build/debug/.obj/moc_mainwindow.o \
		build/debug/.obj/moc_mapwindow.o \
		build/debug/.obj/moc_districtmap.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Messages.pro menu_window/mainwindow.h \
		menu_window/mapwindow.h \
		menu_window/districtmap.h main.cpp \
		menu_window/mainwindow.cpp \
		menu_window/mapwindow.cpp \
		menu_window/districtmap.cpp \
		district/baxter_theatre_district.cpp \
		district/bernard_district.cpp \
		district/blue_district.cpp \
		district/border_district.cpp \
		district/capital_district.cpp \
		district/capital_mausoleum_district.cpp \
		district/central_market_district.cpp \
		district/church_of_anne_district.cpp \
		district/damen_district.cpp \
		district/east_a_district.cpp \
		district/east_b_district.cpp \
		district/east_fishery_district.cpp \
		district/fishery_district.cpp \
		district/flower_square_district.cpp \
		district/hotel_district.cpp \
		district/lower_west_district.cpp \
		district/north_district.cpp \
		district/north_fishery_district.cpp \
		district/north_market_district.cpp \
		district/sea_district.cpp \
		district/south_fishery_district.cpp \
		district/south_market_district.cpp \
		district/st_abraham_district.cpp \
		district/steam_mines_district.cpp \
		district/stone_district.cpp
QMAKE_TARGET  = DNDHLPR
DESTDIR       = build/debug/#avoid trailing-slash linebreak
TARGET        = build/debug/DNDHLPR


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): build/debug/.ui/ui_mainwindow.h build/debug/.ui/ui_mapwindow.h build/debug/.ui/ui_districtmap.h $(OBJECTS)  
	@test -d build/debug/ || mkdir -p build/debug/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Messages.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Messages.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -spec linux-g++-64 -o Makefile Messages.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Messages.pro:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++-64 -o Makefile Messages.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents menu_window/mainwindow.h menu_window/mapwindow.h menu_window/districtmap.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp menu_window/mainwindow.cpp menu_window/mapwindow.cpp menu_window/districtmap.cpp district/baxter_theatre_district.cpp district/bernard_district.cpp district/blue_district.cpp district/border_district.cpp district/capital_district.cpp district/capital_mausoleum_district.cpp district/central_market_district.cpp district/church_of_anne_district.cpp district/damen_district.cpp district/east_a_district.cpp district/east_b_district.cpp district/east_fishery_district.cpp district/fishery_district.cpp district/flower_square_district.cpp district/hotel_district.cpp district/lower_west_district.cpp district/north_district.cpp district/north_fishery_district.cpp district/north_market_district.cpp district/sea_district.cpp district/south_fishery_district.cpp district/south_market_district.cpp district/st_abraham_district.cpp district/steam_mines_district.cpp district/stone_district.cpp $(DISTDIR)/
	$(COPY_FILE) --parents menu_window/mainwindow.ui menu_window/mapwindow.ui menu_window/districtmap.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: build/debug/.moc/moc_mainwindow.cpp build/debug/.moc/moc_mapwindow.cpp build/debug/.moc/moc_districtmap.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/debug/.moc/moc_mainwindow.cpp build/debug/.moc/moc_mapwindow.cpp build/debug/.moc/moc_districtmap.cpp
build/debug/.moc/moc_mainwindow.cpp: menu_window/mapwindow.h \
		init.h \
		district/district.h \
		district/fishery.h \
		district/stone_district.h \
		district/lower_west_district.h \
		district/north_district.h \
		district/border_district.h \
		district/south_market_district.h \
		district/market.h \
		district/capital_district.h \
		district/bernard_district.h \
		district/capital_mausoleum_district.h \
		district/st_abraham_district.h \
		district/church_of_anne_district.h \
		district/flower_square_district.h \
		district/north_market_district.h \
		district/south_fishery_district.h \
		district/central_market_district.h \
		district/hotel_district.h \
		district/sea_district.h \
		district/damen_district.h \
		district/baxter_theatre_district.h \
		district/blue_district.h \
		district/fishery_district.h \
		district/east_a_district.h \
		district/east_b_district.h \
		district/north_fishery_district.h \
		district/east_fishery_district.h \
		district/steam_mines_district.h \
		menu_window/districtmap.h \
		menu_window/mainwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/colt/Desktop/Not CPSC/DNDHelper' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include menu_window/mainwindow.h -o build/debug/.moc/moc_mainwindow.cpp

build/debug/.moc/moc_mapwindow.cpp: init.h \
		district/district.h \
		district/fishery.h \
		district/stone_district.h \
		district/lower_west_district.h \
		district/north_district.h \
		district/border_district.h \
		district/south_market_district.h \
		district/market.h \
		district/capital_district.h \
		district/bernard_district.h \
		district/capital_mausoleum_district.h \
		district/st_abraham_district.h \
		district/church_of_anne_district.h \
		district/flower_square_district.h \
		district/north_market_district.h \
		district/south_fishery_district.h \
		district/central_market_district.h \
		district/hotel_district.h \
		district/sea_district.h \
		district/damen_district.h \
		district/baxter_theatre_district.h \
		district/blue_district.h \
		district/fishery_district.h \
		district/east_a_district.h \
		district/east_b_district.h \
		district/north_fishery_district.h \
		district/east_fishery_district.h \
		district/steam_mines_district.h \
		menu_window/districtmap.h \
		menu_window/mapwindow.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/colt/Desktop/Not CPSC/DNDHelper' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include menu_window/mapwindow.h -o build/debug/.moc/moc_mapwindow.cpp

build/debug/.moc/moc_districtmap.cpp: menu_window/districtmap.h
	/usr/lib/x86_64-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I'/home/colt/Desktop/Not CPSC/DNDHelper' -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include menu_window/districtmap.h -o build/debug/.moc/moc_districtmap.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/debug/.ui/ui_mainwindow.h build/debug/.ui/ui_mapwindow.h build/debug/.ui/ui_districtmap.h
compiler_uic_clean:
	-$(DEL_FILE) build/debug/.ui/ui_mainwindow.h build/debug/.ui/ui_mapwindow.h build/debug/.ui/ui_districtmap.h
build/debug/.ui/ui_mainwindow.h: menu_window/mainwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic menu_window/mainwindow.ui -o build/debug/.ui/ui_mainwindow.h

build/debug/.ui/ui_mapwindow.h: menu_window/mapwindow.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic menu_window/mapwindow.ui -o build/debug/.ui/ui_mapwindow.h

build/debug/.ui/ui_districtmap.h: menu_window/districtmap.ui
	/usr/lib/x86_64-linux-gnu/qt5/bin/uic menu_window/districtmap.ui -o build/debug/.ui/ui_districtmap.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/debug/.obj/main.o: main.cpp menu_window/mainwindow.h \
		menu_window/mapwindow.h \
		init.h \
		district/district.h \
		district/fishery.h \
		district/stone_district.h \
		district/lower_west_district.h \
		district/north_district.h \
		district/border_district.h \
		district/south_market_district.h \
		district/market.h \
		district/capital_district.h \
		district/bernard_district.h \
		district/capital_mausoleum_district.h \
		district/st_abraham_district.h \
		district/church_of_anne_district.h \
		district/flower_square_district.h \
		district/north_market_district.h \
		district/south_fishery_district.h \
		district/central_market_district.h \
		district/hotel_district.h \
		district/sea_district.h \
		district/damen_district.h \
		district/baxter_theatre_district.h \
		district/blue_district.h \
		district/fishery_district.h \
		district/east_a_district.h \
		district/east_b_district.h \
		district/north_fishery_district.h \
		district/east_fishery_district.h \
		district/steam_mines_district.h \
		menu_window/districtmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/main.o main.cpp

build/debug/.obj/mainwindow.o: menu_window/mainwindow.cpp menu_window/mainwindow.h \
		menu_window/mapwindow.h \
		init.h \
		district/district.h \
		district/fishery.h \
		district/stone_district.h \
		district/lower_west_district.h \
		district/north_district.h \
		district/border_district.h \
		district/south_market_district.h \
		district/market.h \
		district/capital_district.h \
		district/bernard_district.h \
		district/capital_mausoleum_district.h \
		district/st_abraham_district.h \
		district/church_of_anne_district.h \
		district/flower_square_district.h \
		district/north_market_district.h \
		district/south_fishery_district.h \
		district/central_market_district.h \
		district/hotel_district.h \
		district/sea_district.h \
		district/damen_district.h \
		district/baxter_theatre_district.h \
		district/blue_district.h \
		district/fishery_district.h \
		district/east_a_district.h \
		district/east_b_district.h \
		district/north_fishery_district.h \
		district/east_fishery_district.h \
		district/steam_mines_district.h \
		menu_window/districtmap.h \
		menu_window/ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/mainwindow.o menu_window/mainwindow.cpp

build/debug/.obj/mapwindow.o: menu_window/mapwindow.cpp menu_window/mapwindow.h \
		init.h \
		district/district.h \
		district/fishery.h \
		district/stone_district.h \
		district/lower_west_district.h \
		district/north_district.h \
		district/border_district.h \
		district/south_market_district.h \
		district/market.h \
		district/capital_district.h \
		district/bernard_district.h \
		district/capital_mausoleum_district.h \
		district/st_abraham_district.h \
		district/church_of_anne_district.h \
		district/flower_square_district.h \
		district/north_market_district.h \
		district/south_fishery_district.h \
		district/central_market_district.h \
		district/hotel_district.h \
		district/sea_district.h \
		district/damen_district.h \
		district/baxter_theatre_district.h \
		district/blue_district.h \
		district/fishery_district.h \
		district/east_a_district.h \
		district/east_b_district.h \
		district/north_fishery_district.h \
		district/east_fishery_district.h \
		district/steam_mines_district.h \
		menu_window/districtmap.h \
		menu_window/ui_mapwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/mapwindow.o menu_window/mapwindow.cpp

build/debug/.obj/districtmap.o: menu_window/districtmap.cpp menu_window/districtmap.h \
		build/debug/.ui/ui_districtmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/districtmap.o menu_window/districtmap.cpp

build/debug/.obj/baxter_theatre_district.o: district/baxter_theatre_district.cpp district/baxter_theatre_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/baxter_theatre_district.o district/baxter_theatre_district.cpp

build/debug/.obj/bernard_district.o: district/bernard_district.cpp district/bernard_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/bernard_district.o district/bernard_district.cpp

build/debug/.obj/blue_district.o: district/blue_district.cpp district/blue_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/blue_district.o district/blue_district.cpp

build/debug/.obj/border_district.o: district/border_district.cpp district/border_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/border_district.o district/border_district.cpp

build/debug/.obj/capital_district.o: district/capital_district.cpp district/capital_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/capital_district.o district/capital_district.cpp

build/debug/.obj/capital_mausoleum_district.o: district/capital_mausoleum_district.cpp district/capital_mausoleum_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/capital_mausoleum_district.o district/capital_mausoleum_district.cpp

build/debug/.obj/central_market_district.o: district/central_market_district.cpp district/central_market_district.h \
		district/market.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/central_market_district.o district/central_market_district.cpp

build/debug/.obj/church_of_anne_district.o: district/church_of_anne_district.cpp district/church_of_anne_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/church_of_anne_district.o district/church_of_anne_district.cpp

build/debug/.obj/damen_district.o: district/damen_district.cpp district/damen_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/damen_district.o district/damen_district.cpp

build/debug/.obj/east_a_district.o: district/east_a_district.cpp district/east_a_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/east_a_district.o district/east_a_district.cpp

build/debug/.obj/east_b_district.o: district/east_b_district.cpp district/east_b_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/east_b_district.o district/east_b_district.cpp

build/debug/.obj/east_fishery_district.o: district/east_fishery_district.cpp district/east_fishery_district.h \
		district/fishery.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/east_fishery_district.o district/east_fishery_district.cpp

build/debug/.obj/fishery_district.o: district/fishery_district.cpp district/fishery_district.h \
		district/fishery.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/fishery_district.o district/fishery_district.cpp

build/debug/.obj/flower_square_district.o: district/flower_square_district.cpp district/flower_square_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/flower_square_district.o district/flower_square_district.cpp

build/debug/.obj/hotel_district.o: district/hotel_district.cpp district/hotel_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/hotel_district.o district/hotel_district.cpp

build/debug/.obj/lower_west_district.o: district/lower_west_district.cpp district/lower_west_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/lower_west_district.o district/lower_west_district.cpp

build/debug/.obj/north_district.o: district/north_district.cpp district/north_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/north_district.o district/north_district.cpp

build/debug/.obj/north_fishery_district.o: district/north_fishery_district.cpp district/north_fishery_district.h \
		district/fishery.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/north_fishery_district.o district/north_fishery_district.cpp

build/debug/.obj/north_market_district.o: district/north_market_district.cpp district/north_market_district.h \
		district/market.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/north_market_district.o district/north_market_district.cpp

build/debug/.obj/sea_district.o: district/sea_district.cpp district/sea_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/sea_district.o district/sea_district.cpp

build/debug/.obj/south_fishery_district.o: district/south_fishery_district.cpp district/south_fishery_district.h \
		district/fishery.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/south_fishery_district.o district/south_fishery_district.cpp

build/debug/.obj/south_market_district.o: district/south_market_district.cpp district/south_market_district.h \
		district/market.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/south_market_district.o district/south_market_district.cpp

build/debug/.obj/st_abraham_district.o: district/st_abraham_district.cpp district/st_abraham_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/st_abraham_district.o district/st_abraham_district.cpp

build/debug/.obj/steam_mines_district.o: district/steam_mines_district.cpp district/steam_mines_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/steam_mines_district.o district/steam_mines_district.cpp

build/debug/.obj/stone_district.o: district/stone_district.cpp district/stone_district.h \
		district/district.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/stone_district.o district/stone_district.cpp

build/debug/.obj/moc_mainwindow.o: build/debug/.moc/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_mainwindow.o build/debug/.moc/moc_mainwindow.cpp

build/debug/.obj/moc_mapwindow.o: build/debug/.moc/moc_mapwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_mapwindow.o build/debug/.moc/moc_mapwindow.cpp

build/debug/.obj/moc_districtmap.o: build/debug/.moc/moc_districtmap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/debug/.obj/moc_districtmap.o build/debug/.moc/moc_districtmap.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

